export default {
    storeList: [
        {
            storeName: "商家一",
            imgUrl: "https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1162078135,4065398554&fm=26&gp=0.jpg",
            description: "【喜糖·地久天长】巧罗纯 可可脂巧克力喜糖款",
            price: "152.00",
            stars: 53,
            active: ["活动促销", "淘金币抵1%"],
            normalPrice: "688",
            expressage: "快递",
            expressagePrice: "免运费",
            salesVolume: "5",
            storeAddress: "杭州",
        },
        {
            storeName: "商家二",
            imgUrl: "https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1162078135,4065398554&fm=26&gp=0.jpg",
            description: "【今世缘典藏18】42度浓 香型薄酒宴喜酒500ml...",
            price: "350.00",
            stars: 80,
            active: ["活动促销", "淘金币抵1%"],
            normalPrice: "688",
            expressage: "快递",
            expressagePrice: "免运费",
            salesVolume: "5",
            storeAddress: "杭州",
        },
        {
            storeName: "商家三",
            imgUrl: "https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1162078135,4065398554&fm=26&gp=0.jpg",
            description: "菲寻 结婚婚庆纸杯加厚婚宴婚礼一次性大红杯子",
            price: "3.55",
            stars: 32,
            active: ["活动促销", "淘金币抵1%"],
            normalPrice: "688",
            expressage: "快递",
            expressagePrice: "免运费",
            salesVolume: "5",
            storeAddress: "杭州",
        },
        {
            storeName: "商家四",
            imgUrl: "https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1162078135,4065398554&fm=26&gp=0.jpg",
            description: "费列罗进口食品巧克力96粒结婚礼盒装喜糖配喜...",
            price: "269.00",
            stars: 120,
            active: ["活动促销", "淘金币抵1%"],
            normalPrice: "688",
            expressage: "快递",
            expressagePrice: "免运费",
            salesVolume: "5",
            storeAddress: "杭州",
        },
        {
            storeName: "月馨婚品",
            imgUrl: "https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1162078135,4065398554&fm=26&gp=0.jpg",
            description: "高端新娘捧花缎带珍珠钻DIY韩式花球婚庆礼品手捧花束",
            price: "488",
            stars: 132,
            active: ["活动促销", "淘金币抵1%"],
            normalPrice: "688",
            expressage: "快递",
            expressagePrice: "免运费",
            salesVolume: "5",
            storeAddress: "杭州",
        },
        {
            storeName: "月馨婚品",
            imgUrl: "https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1162078135,4065398554&fm=26&gp=0.jpg",
            description: "高端新娘捧花缎带珍珠钻DIY韩式花球婚庆礼品手捧花束",
            price: "488",
            stars: 132,
            active: ["活动促销", "淘金币抵1%"],
            normalPrice: "688",
            expressage: "快递",
            expressagePrice: "免运费",
            salesVolume: "5",
            storeAddress: "杭州",
        },
    ]
}